import * as AddressType from './address-type';
import * as Communes from './communes';
import * as Controllers from './controllers';
import * as Districts from './districts';
import * as HospitalOrd from './hospital-ord';
import * as Microsoft from './microsoft';
import * as Patients from './patients';
import * as Provinces from './provinces';
import * as Services from './services';
import * as UserHospitals from './user-hospitals';
export { AddressType, Communes, Controllers, Districts, HospitalOrd, Microsoft, Patients, Provinces, Services, UserHospitals };
